import { FaReact, FaNodeJs, FaPython } from "react-icons/fa";

import {
  SiReact,
  SiNextdotjs,
  SiAngular,
  SiElectron,
  SiJavascript,
  SiTypescript,
  SiNodedotjs,
  SiExpress,
  SiNestjs,
  SiGraphql,
  SiWebrtc,
  SiPython,
  SiFastapi,
  SiAmazon,
  SiGooglecloud,
  SiDocker,
  SiMongodb,
  SiMysql,
  SiPostgresql,
  SiFirebase,
  SiRedis,
  SiElastic,
  SiOpenai,
  SiLangchain,
} from "react-icons/si";
import {
  Code,
  Server,
  Cpu,
  Database,
  Languages,
  BrainCircuit,
  Sparkles,
} from "lucide-react";

const projects = [
  {
    title: "Velotransact",
    slug: "velotransact",
    description: "Smarter Vehicle Transactions Platform.",
    link: "https://velotransact.ontheweb.app/",
    tags: [
      "GCP",
      "Web",
      "React",
      "Firebase",
      "Node JS",
      "Express JS",
      "MongoDB",
    ],
    images: [
      "/projects/screenshots/velotransact/1.png",
      "/projects/screenshots/velotransact/2.png",
      "/projects/screenshots/velotransact/3.png",
      "/projects/screenshots/velotransact/4.png",
      "/projects/screenshots/velotransact/5.png",
      "/projects/screenshots/velotransact/6.png",
      "/projects/screenshots/velotransact/7.png",
      "/projects/screenshots/velotransact/8.png",
      "/projects/screenshots/velotransact/9.png",
    ],
    features: [
      `Manage Inventory Via Integrations (vauto, Homenet, Etc.)
Approve Broker Transactions, Trade-ins, Loyalty Discounts
Coordinate Delivery + Track Payments`,
      `Submit Purchases / Trade-ins
Track Commissions & Payments
Upload Required Documents & Manage Equity`,
      `Document Upload & Approval Flow`,
      `Vehicle Inventory Management`,
      `Broker Transaction Management`,
      `Payment Tracking & Commission Management`,
      `Customer Purchase & Trade-in Portal`,
      `Integration with vAuto & HomeNet`,
      `Dealer & Broker Dashboards`,
      `Advanced Search & Filtering`,
      `Responsive Design for Mobile & Desktop`,
      `Secure Authentication & Role-based Access`,
      `Audit Logs & Activity Tracking`,
      `Integration with Third-party APIs`,
      `Cloud-hosted with GCP & Firebase`,
      `Automated Email Notifications`,
      `Admin Controls & Compliance Oversight`,
      `Real-time Notifications & Updates`,
    ],
    contributions: [""],
    displayImage: "/projects/screenshots/velotransact/3.png",
  },

  {
    title: "Aadvico",
    slug: "aadvico",
    description: "E-Commerce Platform for Makhana Products.",
    link: "https://www.aadvico.com/",
    tags: ["GCP", "Web", "Next.js", "Firebase"],
    images: [
      "/projects/screenshots/aadvico/1.png",
      "/projects/screenshots/aadvico/2.png",
      "/projects/screenshots/aadvico/3.png",
      "/projects/screenshots/aadvico/4.png",
      "/projects/screenshots/aadvico/5.png",
      "/projects/screenshots/aadvico/6.png",
      "/projects/screenshots/aadvico/7.png",
      "/projects/screenshots/aadvico/8.png",
      "/projects/screenshots/aadvico/9.png",
    ],
    features: ["E-Commerce platform for buying premium Makhana products"],
    contributions: [
      "Developed the application end-to-end, integrating GCP services and Firebase for backend functionalities.",
      "Implemented responsive UI/UX for seamless shopping experience across devices.",
      "Integrated secure payment gateways and order management systems.",
      "Optimized performance and scalability for high traffic handling.",
      "Built admin dashboard for inventory and sales tracking.",
      "Implemented user authentication and profile management features.",
    ],
    displayImage: "/projects/screenshots/aadvico/1.png",
  },

  {
    title: "Koodums Chat",
    slug: "koodums-chat",
    description:
      "AI-powered digital concierge chatbot for hotels offering room services, travel planning, ticket booking,and itinerary management.",
    link: "https://admin-tool-dev.genaisolutions.ai/",
    images: [
      "/projects/screenshots/koodums-chat/1.png",
      "/projects/screenshots/koodums-chat/2.png",
      "/projects/screenshots/koodums-chat/3.png",
    ],
    tags: ["AI Agents", "Node JS", "Typescript", "Python", "GCP", "MCP"],
    features: [
      "AI-driven travel assistance and room services via conversational UI",
      "MCP-based external tool integration (Google Maps, YouTube)",
      "Intelligent prompt refinement for incomplete queries",
      "Dynamic context management for LLM conversation history",
      "Scalable architecture for high-performance chatbot operation",
    ],

    contributions: [
      "Focused on building the MCP (Model Context Protocol) client and server architecture to connect AI agents with external tools like Google Maps and YouTube.",
      "Implemented MCP servers from scratch to handle tool calls for fetching place details, directions, reviews, photos, YouTube videos, comments, live streams, shorts, channels, and playlists.",
      "Developed prompt optimization logic to clarify incomplete or ambiguous user queries by analyzing conversational context or dynamically requesting missing information from the user.",
      "Designed and implemented context management system to ensure optimal LLM performance by maintaining only the latest 10 conversational turns for efficient memory usage and relevant context injection.",
      "Enabled AI agents to dynamically chain tool calls through MCP servers to enrich user conversations and deliver personalized, context-aware responses.",
      "Collaborated on integration with cloud services for scalable deployment and real-time system performance.",
    ],
    displayImage: "/projects/screenshots/koodums-chat/3.png",
  },
  {
    title: "SWIFI",
    slug: "swifi",
    description:
      "Big Data platform for extracting and analyzing SEC filings for fintech applications.",
    link: "https://www.xinervatech.com/",
    images: [
      "/projects/screenshots/swifi/1.png",
      "/projects/screenshots/swifi/2.png",
      "/projects/screenshots/swifi/3.png",
    ],
    tags: ["Angular", "Web", "Node JS", "Typescript"],
    contributions: [
      "Developed a web scraper to extract and process investment-grade SEC filings.",
      "Built an annotation tool allowing users to highlight and comment on filing data for collaborative analysis.",
    ],

    displayImage: "/projects/screenshots/swifi/1.png",
  },
  {
    title: "Kiddie Kredit",
    slug: "kiddie-kredit",
    description:
      "Financial education mobile app for children. Gamified with task & reward systems.",
    link: "https://play.google.com/store/apps/details?id=com.kiddiekredit.app&pcampaignid=web_share",
    images: [
      "/projects/screenshots/kk/5.png",
      "/projects/screenshots/kk/2.png",
      "/projects/screenshots/kk/4.png",
      "/projects/screenshots/kk/6.png",
      "/projects/screenshots/kk/7.png",
      "/projects/screenshots/kk/8.png",
      "/projects/screenshots/kk/9.png",
      "/projects/screenshots/kk/10.png",
      "/projects/screenshots/kk/12.png",
      "/projects/screenshots/kk/13.png",
      "/projects/screenshots/kk/14.png",
      "/projects/screenshots/kk/15.png",
    ],
    tags: ["React Native", "Node JS", "Android", "IOS", "Animation"],
    displayImage: "/projects/screenshots/kk/6.png",
    contributions: [
      "Developed gamified task/reward system for children’s financial literacy",
      "Built multi-role support (child, guardian, admin)",
      "End-to-end development of the mobile application.",
      "Built core features such as task assignment, reward systems, credit score simulation, progress tracking, and educational modules.",
      "Integrated Braze for behavior tracking, campaign management, and personalized notifications.",
      "Developed secure authentication, push notifications, and parental controls for data privacy.",
    ],
  },
  {
    title: "Earnings Call",
    slug: "earnings-call",
    description:
      "AI-powered insights platform for earnings calls and SEC filings.",
    link: "https://earnings-call.vercel.app/",
    tags: ["AI", "Web", "Next.js", "AWS"],
    images: [
      "/projects/screenshots/earnings-call/1.png",
      "/projects/screenshots/earnings-call/2.png",
      "/projects/screenshots/earnings-call/3.png",
      "/projects/screenshots/earnings-call/4.png",
      "/projects/screenshots/earnings-call/5.png",
      "/projects/screenshots/earnings-call/6.png",
      "/projects/screenshots/earnings-call/7.png",
      "/projects/screenshots/earnings-call/8.png",
      "/projects/screenshots/earnings-call/9.png",
      "/projects/screenshots/earnings-call/10.png",
      "/projects/screenshots/earnings-call/11.png",
      "/projects/screenshots/earnings-call/12.png",
    ],
    features: [
      "AI-powered earnings call analysis",
      "Sentiment analysis & real-time graphs",
      "Earnings call transcripts & uploads",
      "Company comparisons & financial reports",
      "SEC filings integration",
      "Voice assistant for conversational queries",
    ],
    contributions: [
      "Developed the application end-to-end, integrating AI-powered data processing and visualization.",
      "Implemented real-time sentiment analysis, Q&A functionality, and transcript generation from earnings calls.",
      "Built features to fetch, upload, and manage earnings calls for multiple companies.",
      "Developed earnings calendar, company performance comparison tools, and AI-generated visual reports.",
      "Integrated SEC filing reports including income statements, balance sheets, and cash flow statements.",
      "Added voice assistant functionality for interactive financial insights.",
    ],
    displayImage: "/projects/screenshots/earnings-call/12.png",
  },
  {
    title: "Logik",
    slug: "logik",
    link: "https://play.google.com/store/apps/details?id=com.brightcode.logik&pcampaignid=web_share",
    description:
      "Logistics and vehicle rental platform for seamless delivery services.",
    images: [
      "/projects/screenshots/logik/14.png",
      "/projects/screenshots/logik/1.png",
      "/projects/screenshots/logik/18.png",
      "/projects/screenshots/logik/3.png",
      "/projects/screenshots/logik/25.png",
      "/projects/screenshots/logik/26.png",
      "/projects/screenshots/logik/27.png",
      "/projects/screenshots/logik/28.png",
      "/projects/screenshots/logik/29.png",
      "/projects/screenshots/logik/4.png",
      "/projects/screenshots/logik/5.png",
      "/projects/screenshots/logik/6.png",
      "/projects/screenshots/logik/7.png",
      "/projects/screenshots/logik/8.png",
      "/projects/screenshots/logik/9.png",
      "/projects/screenshots/logik/10.png",
      "/projects/screenshots/logik/11.png",
      "/projects/screenshots/logik/12.png",
      "/projects/screenshots/logik/13.png",
      "/projects/screenshots/logik/15.png",
      "/projects/screenshots/logik/16.png",
      "/projects/screenshots/logik/17.png",
      "/projects/screenshots/logik/20.png",
      "/projects/screenshots/logik/23.png",
      "/projects/screenshots/logik/24.png",
    ],
    tags: ["React Native", "Node JS", "Android", "IOS", "Tracking", "GCP"],
    displayImage: "/projects/screenshots/logik/14.png",
    contributions: [
      "Fully developed both client and driver applications.",
      "Implemented vehicle booking, real-time tracking, route optimization, invoicing, ride history, and secure payments.",
      "Integrated smart vehicle-driver matching algorithms.",
      "Developed real-time notifications, secure user authentication, and transaction management.",
    ],
  },
  {
    title: "OFLEP Connect",
    slug: "oflep-connect",
    description:
      "Video conferencing platform offering HD calls, collaboration tools, and secure virtual meetings for individuals and businesses.",
    link: null,
    images: [
      "/projects/screenshots/oflep/1.png",
      "/projects/screenshots/oflep/2.png",
      "/projects/screenshots/oflep/4.png",
      "/projects/screenshots/oflep/5.png",
      "/projects/screenshots/oflep/7.png",
      "/projects/screenshots/oflep/8.png",
      "/projects/screenshots/oflep/11.png",
      "/projects/screenshots/oflep/12.png",
      "/projects/screenshots/oflep/13.png",
      "/projects/screenshots/oflep/15.png",
    ],
    tags: [
      "React Native",
      "Express.js",
      "Node.js",
      "WebRTC",
      "MongoDB",
      "Socket.io",
      "TypeScript",
    ],
    features: [
      "Real-time chat & reactions during calls",
      "Multi-participant grid layout for up to 10 participants",
      "Raise-hand feature for organized communication",
      "Screen sharing, host moderation, and secure access control",
      "Cross-platform video calls (Web & Mobile)",
    ],
    contributions: [
      "Designed and developed high-quality multi-party video calling functionality using WebRTC.",
      "Built core features such as screen sharing, chat, reactions, and meeting scheduling with recording support.",
      "Implemented advanced host controls for muting, video toggling, participant management, and permissions.",
      "Integrated secure, password-protected meeting invites with time-limited access links.",
      "Developed cross-platform solutions to support both mobile (iOS & Android) and web-based participation.",
      "Configured TURN servers for improved call stability and reliability under various network conditions.",
    ],
    displayImage: "/projects/screenshots/oflep/1.png",
  },
  {
    title: "Intellibooks",
    slug: "intellibooks",
    description:
      "Cross-platform desktop application for hotel and restaurant owners to manage orders, inventory, and billing operations.",
    link: "https://intellibooks.io/",
    images: [
      "/projects/screenshots/intellibooks/1.png",
      "/projects/screenshots/intellibooks/2.png",
    ],
    tags: ["React", " Electron.js", "Express.js", "Node.js", "TypeScript"],
    contributions: [
      "Developed a multi-platform desktop application compatible across various operating systems.",
      "Implemented hash-based routing and platform-specific adaptations for cross-OS compatibility.",
      "Developed modules for order management, stock handling, billing, and reporting.",
    ],
    displayImage: "/projects/screenshots/intellibooks/2.png",
  },
  {
    title: "AutoFlow",
    slug: "autoflow",
    description:
      "Lead generation and outbound marketing platform with Apollo.io integration.",
    link: null,
    images: [
      "/projects/screenshots/autoflow/1.png",
      "/projects/screenshots/autoflow/2.png",
      "/projects/screenshots/autoflow/3.png",
      "/projects/screenshots/autoflow/4.png",
      "/projects/screenshots/autoflow/5.png",
      "/projects/screenshots/autoflow/6.png",
      "/projects/screenshots/autoflow/7.png",
      "/projects/screenshots/autoflow/8.png",
      "/projects/screenshots/autoflow/9.png",
      "/projects/screenshots/autoflow/10.png",
      "/projects/screenshots/autoflow/11.png",
      "/projects/screenshots/autoflow/12.png",
      "/projects/screenshots/autoflow/13.png",
      "/projects/screenshots/autoflow/14.png",
      "/projects/screenshots/autoflow/15.png",
      "/projects/screenshots/autoflow/16.png",
    ],
    tags: ["Automation", "Web", "Next.js", "Node.js", "Express.js"],
    features: [
      "Multi-platform data extraction (Nasdaq, YCombinator, Google Sheets, LinkedIn, Clutch)",
      "Automated data enrichment via Apollo.io (emails, LinkedIn URLs, phone numbers)",
      "Outbound marketing: email campaigns and voice drops",
      "Campaign performance monitoring and lead management",
      "End-to-end automation from lead discovery to outreach",
    ],
    contributions: [
      "Developed the full application from scratch, handling complete frontend, backend, and integrations.",
      "Implemented multi-source data extraction pipelines from platforms like Nasdaq, Google Sheets, Y Combinator, Clutch, and LinkedIn.",
      "Built enrichment workflows by integrating Apollo.io API to retrieve emails, LinkedIn profiles, and phone numbers for extracted leads.",
      "Designed marketing automation workflows for running email and voice drop campaigns targeting enriched leads.",
      "Enabled seamless campaign management with real-time tracking and performance reporting.",
    ],

    displayImage: "/projects/screenshots/autoflow/1.png",
  },

  {
    title: "PetLinx",
    slug: "petlinx",
    description:
      "Pet grooming and daycare platform with customizable email templates.",
    link: "https://petlinx.com/",
    images: [
      "/projects/screenshots/petlinx/1.png",
      "/projects/screenshots/petlinx/2.png",
    ],
    tags: ["AI", "Web", "Next.js"],
    contributions: [
      "Built email template editor for customizable communications.",
      "Performed bug fixing and code optimization for improved performance.",
    ],
    displayImage: "/projects/screenshots/petlinx/1.png",
  },

  // {
  //   title: "DELIGO",
  //   slug: "deligo",
  //   description:
  //     "End-to-end food & grocery  delivery ecosystem with multi-role apps.",
  //   images: [
  //     "/projects/screenshots/deligo/4.png",
  //     "/projects/screenshots/deligo/1.png",
  //     "/projects/screenshots/deligo/6.png",
  //     "/projects/screenshots/deligo/2.png",
  //     "/projects/screenshots/deligo/9.png",
  //     "/projects/screenshots/deligo/10.png",
  //     "/projects/screenshots/deligo/11.png",
  //     "/projects/screenshots/deligo/12.png",
  //     "/projects/screenshots/deligo/13.png",
  //   ],
  //   tags: ["React Native", "Node JS", "Android", "IOS", "AWS"],
  //   contributions: [
  //     "End-to-end development of customer, vendor, delivery partner apps, and admin panel.",
  //     "Built key modules for order management, real-time tracking, payments, vendor inventory, and delivery partner assignments.",
  //     "Integrated Razorpay for secure multi-payment options including digital wallets and COD.",
  //     "Implemented Firebase for real-time updates, push notifications, and seamless order tracking.",
  //     "Designed role-based access control for secure user, vendor, delivery partner, and admin functionalities.",
  //     "Built analytics dashboards for performance monitoring, vendor reporting, and transaction management.",
  //   ],
  //   displayImage: "/projects/screenshots/deligo/4.png",
  // },
];

const techStack = [
  { icon: FaReact, color: "#61DAFB", name: "React" },
  { icon: SiNextdotjs, color: "#FFFFFF", name: "Next.js" },
  { icon: FaNodeJs, color: "#339933", name: "Node.js" },
  { icon: SiTypescript, color: "#3178C6", name: "TypeScript" },
  { icon: SiMongodb, color: "#47A248", name: "MongoDB" },
  { icon: SiAngular, color: "#DD0031", name: "Angular" },
  { icon: SiFirebase, color: "#FFCA28", name: "Firebase" },
  { icon: FaPython, color: "#3776AB", name: "Python" },
];

const experiences = [
  {
    title: "Software Engineer",
    company: "Jai Infoway Pvt. Ltd.",
    duration: "August 2024 – July 2025",
    description:
      "Leading full-stack development for global client projects in a product-service hybrid environment.",
    tech: "React • Node.js • AWS • Microservices",
  },
  {
    title: "Mobile App Developer",
    company: "Brightcode Pvt. Ltd.",
    duration: "March 2024 – August 2024",
    description:
      "Developed cross-platform mobile applications with optimized performance and responsive UIs.",
    tech: "React Native • Node.js • GCP",
  },
  {
    title: "Software Engineer",
    company: "Jai Infoway Pvt. Ltd.",
    duration: "February 2023 – February 2024",
    description:
      "Built client-facing applications end-to-end in Agile teams, from UI to backend services.",
    tech: "Angular • Express.js • MongoDB • MySQL",
  },
  {
    title: "Freelance Full-Stack Developer",
    company: "",
    duration: "July 2022 – January 2023",
    description:
      "Delivered complete web solutions for local businesses, handling all development phases.",
    tech: "React • Node.js • REST APIs",
  },
];

const keyProjects = [
  {
    name: "Koodums Chat",
    description: "Generative AI Agents Builder.",
    tech: "React • Node.js • TypeScript • Python • Vertex AI • GCP • Express.js",
  },
  {
    name: "Earnings Call",
    description:
      "AI-powered financial analysis platform with LLM integration and voice assistant.",
    tech: "Next.js • AWS • AI Agents",
  },
  {
    name: "Kiddie-Kredit",
    description:
      "Financial education mobile app for children. Gamified with task & reward systems.",
    tech: "React Native • Node.js • Socket.io",
  },
];

const categories = [
  {
    title: "Frontend",
    icon: Code,
    color: "#38bdf8",
    skills: [
      { icon: <SiReact className="text-[#61dafb]" />, name: "React" },
      { icon: <SiNextdotjs className="text-white" />, name: "Next.js" },
      { icon: <SiAngular className="text-[#dd1b16]" />, name: "Angular" },
      {
        icon: <SiElectron className="text-[#47848F]" />,
        name: "Electron.js",
      },
      {
        icon: <SiJavascript className="text-[#f7df1e]" />,
        name: "JavaScript",
      },
      {
        icon: <SiTypescript className="text-[#3178c6]" />,
        name: "TypeScript",
      },
    ],
  },
  {
    title: "Backend",
    icon: Server,
    color: "#4ade80",
    skills: [
      { icon: <SiNodedotjs className="text-[#339933]" />, name: "Node.js" },
      { icon: <SiGraphql className="text-[#e10098]" />, name: "GraphQL" },
      { icon: <SiExpress className="text-white" />, name: "Express.js" },
      { icon: <SiNestjs className="text-[#e0234e]" />, name: "Nest.js" },
      { icon: <SiWebrtc className="text-[#333]" />, name: "WebRTC" },
      { icon: <SiFastapi className="text-[#009688]" />, name: "FastAPI" },
    ],
  },
  {
    title: "AI/ML",
    icon: BrainCircuit,
    color: "#c084fc",
    skills: [
      { icon: <Sparkles className="text-[#a78bfa]" />, name: "LLMs" },
      { icon: <SiLangchain className="text-[#5c2d91]" />, name: "LangChain" },
      { icon: <SiOpenai className="text-[#10a37f]" />, name: "OpenAI" },
    ],
  },
  {
    title: "Cloud/DevOps",
    icon: Cpu,
    color: "#f59e0b",
    skills: [
      { icon: <SiAmazon className="text-[#ff9900]" />, name: "AWS" },
      { icon: <SiGooglecloud className="text-[#4285f4]" />, name: "GCP" },
      {
        icon: <SiAmazon className="text-[#0078d7]" />,
        name: "Azure",
      },
      { icon: <SiDocker className="text-[#0db7ed]" />, name: "Docker" },
    ],
  },
  {
    title: "Databases",
    icon: Database,
    color: "#f472b6",
    skills: [
      { icon: <SiMongodb className="text-[#47a248]" />, name: "MongoDB" },
      { icon: <SiMysql className="text-[#00758f]" />, name: "MySQL" },
      {
        icon: <SiPostgresql className="text-[#336791]" />,
        name: "PostgreSQL",
      },
      { icon: <SiFirebase className="text-[#ffca28]" />, name: "Firebase" },
      { icon: <SiRedis className="text-[#005571]" />, name: "Redis" },
      { icon: <SiElastic className="text-[#003b57]" />, name: "Elastic" },
    ],
  },
  {
    title: "Languages",
    icon: Languages,
    color: "#ec4899",
    skills: [
      {
        icon: <SiTypescript className="text-[#3178c6]" />,
        name: "TypeScript",
      },
      {
        icon: <SiJavascript className="text-[#f7df1e]" />,
        name: "JavaScript",
      },
      { icon: <SiPython className="text-[#3776ab]" />, name: "Python" },
    ],
  },
];

export { projects, techStack, keyProjects, experiences, categories };
